// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
